<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openBtn</name>
   <tag></tag>
   <elementGuidId>0cb47df1-1339-402a-9419-741f0dd889d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='ctl00_ContentPlaceholder1_RadComboBoxProduct_DropDown']/div[2]/ul/li[1]/table/tbody/tr[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceholder1_RadComboBoxProduct_DropDown']/div[2]/ul/li[1]/table/tbody/tr[1]</value>
   </webElementProperties>
</WebElementEntity>
